/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testing15thnov_stage.db123__.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import com.testing15thnov_stage.db123__.models.procedure.*;

public interface Db123__ProcedureExecutorService {

    Void executeProcedure_Insert(ProcedureInsertRequest procedureInsertRequest);

    ProcedureOnlyInparamResponse executeProcedure_OnlyINParam(Integer id);

    ProcedureInoutResponse executeProcedure_INOUT(String charcolOutput, Integer pkid);

}


