/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testing15thnov_stage.dbscenarios.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.InputStream;
import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testing15thnov_stage.dbscenarios.models.query.*;

public interface DbscenariosQueryExecutorService {

    Page<SvInoperatorResponse> executeSV_INOperator(List<Integer> pkid, Pageable pageable);

    InputStream getBlobColContentForSV_INOperator(Integer pkId, List<Integer> pkid) throws EntityNotFoundException;

    Downloadable exportSV_INOperator(ExportType exportType, List<Integer> pkid, Pageable pageable);

}


