/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing15thnov_stage.dbscenarios.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Lazy;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testing15thnov_stage.dbscenarios.TUcComposites1;
import com.testing15thnov_stage.dbscenarios.TUcComposites2;
import com.testing15thnov_stage.dbscenarios.TUcComposites2Id;


/**
 * ServiceImpl object for domain model class TUcComposites2.
 *
 * @see TUcComposites2
 */
@Service("dbscenarios.TUcComposites2Service")
@Validated
public class TUcComposites2ServiceImpl implements TUcComposites2Service {

    private static final Logger LOGGER = LoggerFactory.getLogger(TUcComposites2ServiceImpl.class);

    @Lazy
    @Autowired
	@Qualifier("dbscenarios.TUcComposites1Service")
	private TUcComposites1Service tUcComposites1Service;

    @Autowired
    @Qualifier("dbscenarios.TUcComposites2Dao")
    private WMGenericDao<TUcComposites2, TUcComposites2Id> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<TUcComposites2, TUcComposites2Id> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "dbscenariosTransactionManager")
    @Override
	public TUcComposites2 create(TUcComposites2 tucComposites2) {
        LOGGER.debug("Creating a new TUcComposites2 with information: {}", tucComposites2);
        TUcComposites2 tucComposites2Created = this.wmGenericDao.create(tucComposites2);
        if(tucComposites2Created.getTucComposites1() != null) {
            TUcComposites1 tucComposites1 = tucComposites2Created.getTucComposites1();
            LOGGER.debug("Creating a new child TUcComposites1 with information: {}", tucComposites1);
            tucComposites1.setTucComposites2(tucComposites2Created);
            tUcComposites1Service.create(tucComposites1);
        }
        return tucComposites2Created;
    }

	@Transactional(readOnly = true, value = "dbscenariosTransactionManager")
	@Override
	public TUcComposites2 getById(TUcComposites2Id tuccomposites2Id) throws EntityNotFoundException {
        LOGGER.debug("Finding TUcComposites2 by id: {}", tuccomposites2Id);
        TUcComposites2 tucComposites2 = this.wmGenericDao.findById(tuccomposites2Id);
        if (tucComposites2 == null){
            LOGGER.debug("No TUcComposites2 found with id: {}", tuccomposites2Id);
            throw new EntityNotFoundException(String.valueOf(tuccomposites2Id));
        }
        return tucComposites2;
    }

    @Transactional(readOnly = true, value = "dbscenariosTransactionManager")
	@Override
	public TUcComposites2 findById(TUcComposites2Id tuccomposites2Id) {
        LOGGER.debug("Finding TUcComposites2 by id: {}", tuccomposites2Id);
        return this.wmGenericDao.findById(tuccomposites2Id);
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "dbscenariosTransactionManager")
	@Override
	public TUcComposites2 update(TUcComposites2 tucComposites2) throws EntityNotFoundException {
        LOGGER.debug("Updating TUcComposites2 with information: {}", tucComposites2);
        this.wmGenericDao.update(tucComposites2);

        TUcComposites2Id tuccomposites2Id = new TUcComposites2Id();
        tuccomposites2Id.setByteId(tucComposites2.getByteId());
        tuccomposites2Id.setCharCol(tucComposites2.getCharCol());
        tuccomposites2Id.setShortCol(tucComposites2.getShortCol());
        tuccomposites2Id.setStringCol(tucComposites2.getStringCol());

        return this.wmGenericDao.findById(tuccomposites2Id);
    }

    @Transactional(value = "dbscenariosTransactionManager")
	@Override
	public TUcComposites2 delete(TUcComposites2Id tuccomposites2Id) throws EntityNotFoundException {
        LOGGER.debug("Deleting TUcComposites2 with id: {}", tuccomposites2Id);
        TUcComposites2 deleted = this.wmGenericDao.findById(tuccomposites2Id);
        if (deleted == null) {
            LOGGER.debug("No TUcComposites2 found with id: {}", tuccomposites2Id);
            throw new EntityNotFoundException(String.valueOf(tuccomposites2Id));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "dbscenariosTransactionManager")
	@Override
	public Page<TUcComposites2> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all TUcComposites2s");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "dbscenariosTransactionManager")
    @Override
    public Page<TUcComposites2> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all TUcComposites2s");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "dbscenariosTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service dbscenarios for table TUcComposites2 to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "dbscenariosTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "dbscenariosTransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }


    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service TUcComposites1Service instance
	 */
	protected void setTUcComposites1Service(TUcComposites1Service service) {
        this.tUcComposites1Service = service;
    }

}

