/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing15thnov_stage.dbscenarios.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testing15thnov_stage.dbscenarios.Uc;


/**
 * ServiceImpl object for domain model class Uc.
 *
 * @see Uc
 */
@Service("dbscenarios.UcService")
@Validated
public class UcServiceImpl implements UcService {

    private static final Logger LOGGER = LoggerFactory.getLogger(UcServiceImpl.class);


    @Autowired
    @Qualifier("dbscenarios.UcDao")
    private WMGenericDao<Uc, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Uc, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "dbscenariosTransactionManager")
    @Override
	public Uc create(Uc uc) {
        LOGGER.debug("Creating a new Uc with information: {}", uc);
        Uc ucCreated = this.wmGenericDao.create(uc);
        return ucCreated;
    }

	@Transactional(readOnly = true, value = "dbscenariosTransactionManager")
	@Override
	public Uc getById(Integer ucId) throws EntityNotFoundException {
        LOGGER.debug("Finding Uc by id: {}", ucId);
        Uc uc = this.wmGenericDao.findById(ucId);
        if (uc == null){
            LOGGER.debug("No Uc found with id: {}", ucId);
            throw new EntityNotFoundException(String.valueOf(ucId));
        }
        return uc;
    }

    @Transactional(readOnly = true, value = "dbscenariosTransactionManager")
	@Override
	public Uc findById(Integer ucId) {
        LOGGER.debug("Finding Uc by id: {}", ucId);
        return this.wmGenericDao.findById(ucId);
    }

    @Transactional(readOnly = true, value = "dbscenariosTransactionManager")
    @Override
    public Uc getByColumn2(int column2) {
        Map<String, Object> column2Map = new HashMap<>();
        column2Map.put("column2", column2);

        LOGGER.debug("Finding Uc by unique keys: {}", column2Map);
        Uc uc = this.wmGenericDao.findByUniqueKey(column2Map);

        if (uc == null){
            LOGGER.debug("No Uc found with given unique key values: {}", column2Map);
            throw new EntityNotFoundException(String.valueOf(column2Map));
        }

        return uc;
    }

	@Transactional(rollbackFor = EntityNotFoundException.class, value = "dbscenariosTransactionManager")
	@Override
	public Uc update(Uc uc) throws EntityNotFoundException {
        LOGGER.debug("Updating Uc with information: {}", uc);
        this.wmGenericDao.update(uc);

        Integer ucId = uc.getId();

        return this.wmGenericDao.findById(ucId);
    }

    @Transactional(value = "dbscenariosTransactionManager")
	@Override
	public Uc delete(Integer ucId) throws EntityNotFoundException {
        LOGGER.debug("Deleting Uc with id: {}", ucId);
        Uc deleted = this.wmGenericDao.findById(ucId);
        if (deleted == null) {
            LOGGER.debug("No Uc found with id: {}", ucId);
            throw new EntityNotFoundException(String.valueOf(ucId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "dbscenariosTransactionManager")
	@Override
	public Page<Uc> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Ucs");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "dbscenariosTransactionManager")
    @Override
    public Page<Uc> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Ucs");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "dbscenariosTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service dbscenarios for table Uc to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "dbscenariosTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "dbscenariosTransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}

