/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing15thnov_stage.sample;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Businessunit generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`BUSINESSUNIT`")
public class Businessunit implements Serializable {

    private Integer oid;
    private String name;
    private Integer headcount;

    @Id
    @Column(name = "`OID`", nullable = false, scale = 0, precision = 10)
    public Integer getOid() {
        return this.oid;
    }

    public void setOid(Integer oid) {
        this.oid = oid;
    }

    @Column(name = "`NAME`", nullable = true, length = 20)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "`HEADCOUNT`", nullable = true, scale = 0, precision = 10)
    public Integer getHeadcount() {
        return this.headcount;
    }

    public void setHeadcount(Integer headcount) {
        this.headcount = headcount;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Businessunit)) return false;
        final Businessunit businessunit = (Businessunit) o;
        return Objects.equals(getOid(), businessunit.getOid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOid());
    }
}

