/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing15thnov_stage.db123__;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Date;
import java.sql.Time;
import java.util.Objects;

import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;

public class ViewDefaultValuesId implements Serializable {

    private Integer assignedId;
    private Byte byteCol;
    private Short shortCol;
    private Integer intCol;
    private Double floatCol;
    private Long longCol;
    private BigDecimal doubleCol;
    private BigInteger bigintCol;
    private BigDecimal bigdecCol;
    private String charCol;
    private String stringCol;
    private String textCol;
    private String clobCol;
    private Date dateCol;
    @Type(type = "DateTime")
    private LocalDateTime datetimeCol;
    private Time timeCol;
    @Type(type = "DateTime")
    private LocalDateTime timestampCol;
    private Boolean booleanCol;
    private byte[] blobCol;

    public Integer getAssignedId() {
        return this.assignedId;
    }

    public void setAssignedId(Integer assignedId) {
        this.assignedId = assignedId;
    }

    public Byte getByteCol() {
        return this.byteCol;
    }

    public void setByteCol(Byte byteCol) {
        this.byteCol = byteCol;
    }

    public Short getShortCol() {
        return this.shortCol;
    }

    public void setShortCol(Short shortCol) {
        this.shortCol = shortCol;
    }

    public Integer getIntCol() {
        return this.intCol;
    }

    public void setIntCol(Integer intCol) {
        this.intCol = intCol;
    }

    public Double getFloatCol() {
        return this.floatCol;
    }

    public void setFloatCol(Double floatCol) {
        this.floatCol = floatCol;
    }

    public Long getLongCol() {
        return this.longCol;
    }

    public void setLongCol(Long longCol) {
        this.longCol = longCol;
    }

    public BigDecimal getDoubleCol() {
        return this.doubleCol;
    }

    public void setDoubleCol(BigDecimal doubleCol) {
        this.doubleCol = doubleCol;
    }

    public BigInteger getBigintCol() {
        return this.bigintCol;
    }

    public void setBigintCol(BigInteger bigintCol) {
        this.bigintCol = bigintCol;
    }

    public BigDecimal getBigdecCol() {
        return this.bigdecCol;
    }

    public void setBigdecCol(BigDecimal bigdecCol) {
        this.bigdecCol = bigdecCol;
    }

    public String getCharCol() {
        return this.charCol;
    }

    public void setCharCol(String charCol) {
        this.charCol = charCol;
    }

    public String getStringCol() {
        return this.stringCol;
    }

    public void setStringCol(String stringCol) {
        this.stringCol = stringCol;
    }

    public String getTextCol() {
        return this.textCol;
    }

    public void setTextCol(String textCol) {
        this.textCol = textCol;
    }

    public String getClobCol() {
        return this.clobCol;
    }

    public void setClobCol(String clobCol) {
        this.clobCol = clobCol;
    }

    public Date getDateCol() {
        return this.dateCol;
    }

    public void setDateCol(Date dateCol) {
        this.dateCol = dateCol;
    }

    public LocalDateTime getDatetimeCol() {
        return this.datetimeCol;
    }

    public void setDatetimeCol(LocalDateTime datetimeCol) {
        this.datetimeCol = datetimeCol;
    }

    public Time getTimeCol() {
        return this.timeCol;
    }

    public void setTimeCol(Time timeCol) {
        this.timeCol = timeCol;
    }

    public LocalDateTime getTimestampCol() {
        return this.timestampCol;
    }

    public void setTimestampCol(LocalDateTime timestampCol) {
        this.timestampCol = timestampCol;
    }

    public Boolean getBooleanCol() {
        return this.booleanCol;
    }

    public void setBooleanCol(Boolean booleanCol) {
        this.booleanCol = booleanCol;
    }

    public byte[] getBlobCol() {
        return this.blobCol;
    }

    public void setBlobCol(byte[] blobCol) {
        this.blobCol = blobCol;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ViewDefaultValues)) return false;
        final ViewDefaultValues viewDefaultValues = (ViewDefaultValues) o;
        return Objects.equals(getAssignedId(), viewDefaultValues.getAssignedId()) &&
                Objects.equals(getByteCol(), viewDefaultValues.getByteCol()) &&
                Objects.equals(getShortCol(), viewDefaultValues.getShortCol()) &&
                Objects.equals(getIntCol(), viewDefaultValues.getIntCol()) &&
                Objects.equals(getFloatCol(), viewDefaultValues.getFloatCol()) &&
                Objects.equals(getLongCol(), viewDefaultValues.getLongCol()) &&
                Objects.equals(getDoubleCol(), viewDefaultValues.getDoubleCol()) &&
                Objects.equals(getBigintCol(), viewDefaultValues.getBigintCol()) &&
                Objects.equals(getBigdecCol(), viewDefaultValues.getBigdecCol()) &&
                Objects.equals(getCharCol(), viewDefaultValues.getCharCol()) &&
                Objects.equals(getStringCol(), viewDefaultValues.getStringCol()) &&
                Objects.equals(getTextCol(), viewDefaultValues.getTextCol()) &&
                Objects.equals(getClobCol(), viewDefaultValues.getClobCol()) &&
                Objects.equals(getDateCol(), viewDefaultValues.getDateCol()) &&
                Objects.equals(getDatetimeCol(), viewDefaultValues.getDatetimeCol()) &&
                Objects.equals(getTimeCol(), viewDefaultValues.getTimeCol()) &&
                Objects.equals(getTimestampCol(), viewDefaultValues.getTimestampCol()) &&
                Objects.equals(getBooleanCol(), viewDefaultValues.getBooleanCol()) &&
                Objects.equals(getBlobCol(), viewDefaultValues.getBlobCol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAssignedId(),
                getByteCol(),
                getShortCol(),
                getIntCol(),
                getFloatCol(),
                getLongCol(),
                getDoubleCol(),
                getBigintCol(),
                getBigdecCol(),
                getCharCol(),
                getStringCol(),
                getTextCol(),
                getClobCol(),
                getDateCol(),
                getDatetimeCol(),
                getTimeCol(),
                getTimestampCol(),
                getBooleanCol(),
                getBlobCol());
    }
}
