/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing15thnov_stage.dbscenarios;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Account generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`account`")
public class Account implements Serializable {

    private Integer acctNum;
    private Double amount;

    @Id
    @Column(name = "`acct_num`", nullable = false, scale = 0, precision = 10)
    public Integer getAcctNum() {
        return this.acctNum;
    }

    public void setAcctNum(Integer acctNum) {
        this.acctNum = acctNum;
    }

    @Column(name = "`amount`", nullable = true, scale = 2, precision = 10)
    public Double getAmount() {
        return this.amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Account)) return false;
        final Account account = (Account) o;
        return Objects.equals(getAcctNum(), account.getAcctNum());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAcctNum());
    }
}

