/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing15thnov_stage.dbscenarios;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Table32 generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`TABLE32`")
public class Table32 implements Serializable {

    private String id;
    private Table33 table33;

    @Id
    @Column(name = "`ID`", nullable = false, length = 1)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }


    @OneToOne(fetch = FetchType.EAGER, mappedBy = "table32")
    public Table33 getTable33() {
        return this.table33;
    }

    public void setTable33(Table33 table33) {
        this.table33 = table33;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Table32)) return false;
        final Table32 table32 = (Table32) o;
        return Objects.equals(getId(), table32.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

