/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing15thnov_stage.dbscenarios;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

public class TCompositesMany2oneId implements Serializable {

    private Short byteId;
    private Short shortId;
    private String charId;
    private BigDecimal bigdecId;

    public Short getByteId() {
        return this.byteId;
    }

    public void setByteId(Short byteId) {
        this.byteId = byteId;
    }

    public Short getShortId() {
        return this.shortId;
    }

    public void setShortId(Short shortId) {
        this.shortId = shortId;
    }

    public String getCharId() {
        return this.charId;
    }

    public void setCharId(String charId) {
        this.charId = charId;
    }

    public BigDecimal getBigdecId() {
        return this.bigdecId;
    }

    public void setBigdecId(BigDecimal bigdecId) {
        this.bigdecId = bigdecId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TCompositesMany2one)) return false;
        final TCompositesMany2one tcompositesMany2one = (TCompositesMany2one) o;
        return Objects.equals(getByteId(), tcompositesMany2one.getByteId()) &&
                Objects.equals(getShortId(), tcompositesMany2one.getShortId()) &&
                Objects.equals(getCharId(), tcompositesMany2one.getCharId()) &&
                Objects.equals(getBigdecId(), tcompositesMany2one.getBigdecId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getByteId(),
                getShortId(),
                getCharId(),
                getBigdecId());
    }
}
