/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing15thnov_stage.dbscenarios;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * TOne2oneComposites1 generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`T_ONE2ONE_COMPOSITES1`")
@IdClass(TOne2oneComposites1Id.class)
public class TOne2oneComposites1 implements Serializable {

    private Short byteId;
    private Short shortId;
    private String charId;
    private String stringId;
    private String column5;
    private TOne2oneComposites tone2oneComposites;

    @Id
    @Column(name = "`BYTE ID`", nullable = false, scale = 0, precision = 3)
    public Short getByteId() {
        return this.byteId;
    }

    public void setByteId(Short byteId) {
        this.byteId = byteId;
    }

    @Id
    @Column(name = "`SHORT ID`", nullable = false, scale = 0, precision = 5)
    public Short getShortId() {
        return this.shortId;
    }

    public void setShortId(Short shortId) {
        this.shortId = shortId;
    }

    @Id
    @Column(name = "`CHAR ID`", nullable = false, length = 1)
    public String getCharId() {
        return this.charId;
    }

    public void setCharId(String charId) {
        this.charId = charId;
    }

    @Id
    @Column(name = "`STRING ID`", nullable = false, length = 255)
    public String getStringId() {
        return this.stringId;
    }

    public void setStringId(String stringId) {
        this.stringId = stringId;
    }

    @Column(name = "`COLUMN5`", nullable = true, length = 255)
    public String getColumn5() {
        return this.column5;
    }

    public void setColumn5(String column5) {
        this.column5 = column5;
    }

    @OneToOne(fetch = FetchType.EAGER, mappedBy = "tone2oneComposites1")
    public TOne2oneComposites getTone2oneComposites() {
        return this.tone2oneComposites;
    }

    public void setTone2oneComposites(TOne2oneComposites tone2oneComposites) {
        this.tone2oneComposites = tone2oneComposites;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TOne2oneComposites1)) return false;
        final TOne2oneComposites1 tone2oneComposites1 = (TOne2oneComposites1) o;
        return Objects.equals(getByteId(), tone2oneComposites1.getByteId()) &&
                Objects.equals(getShortId(), tone2oneComposites1.getShortId()) &&
                Objects.equals(getCharId(), tone2oneComposites1.getCharId()) &&
                Objects.equals(getStringId(), tone2oneComposites1.getStringId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getByteId(),
                getShortId(),
                getCharId(),
                getStringId());
    }
}

