/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing15thnov_stage.dbscenarios;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class TOne2oneComposites1Id implements Serializable {

    private Short byteId;
    private Short shortId;
    private String charId;
    private String stringId;

    public Short getByteId() {
        return this.byteId;
    }

    public void setByteId(Short byteId) {
        this.byteId = byteId;
    }

    public Short getShortId() {
        return this.shortId;
    }

    public void setShortId(Short shortId) {
        this.shortId = shortId;
    }

    public String getCharId() {
        return this.charId;
    }

    public void setCharId(String charId) {
        this.charId = charId;
    }

    public String getStringId() {
        return this.stringId;
    }

    public void setStringId(String stringId) {
        this.stringId = stringId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TOne2oneComposites1)) return false;
        final TOne2oneComposites1 tone2oneComposites1 = (TOne2oneComposites1) o;
        return Objects.equals(getByteId(), tone2oneComposites1.getByteId()) &&
                Objects.equals(getShortId(), tone2oneComposites1.getShortId()) &&
                Objects.equals(getCharId(), tone2oneComposites1.getCharId()) &&
                Objects.equals(getStringId(), tone2oneComposites1.getStringId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getByteId(),
                getShortId(),
                getCharId(),
                getStringId());
    }
}
