/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing15thnov_stage.dbscenarios;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class TUcComposites2Id implements Serializable {

    private Short byteId;
    private String charCol;
    private Short shortCol;
    private String stringCol;

    public Short getByteId() {
        return this.byteId;
    }

    public void setByteId(Short byteId) {
        this.byteId = byteId;
    }

    public String getCharCol() {
        return this.charCol;
    }

    public void setCharCol(String charCol) {
        this.charCol = charCol;
    }

    public Short getShortCol() {
        return this.shortCol;
    }

    public void setShortCol(Short shortCol) {
        this.shortCol = shortCol;
    }

    public String getStringCol() {
        return this.stringCol;
    }

    public void setStringCol(String stringCol) {
        this.stringCol = stringCol;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TUcComposites2)) return false;
        final TUcComposites2 tucComposites2 = (TUcComposites2) o;
        return Objects.equals(getByteId(), tucComposites2.getByteId()) &&
                Objects.equals(getCharCol(), tucComposites2.getCharCol()) &&
                Objects.equals(getShortCol(), tucComposites2.getShortCol()) &&
                Objects.equals(getStringCol(), tucComposites2.getStringCol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getByteId(),
                getCharCol(),
                getShortCol(),
                getStringCol());
    }
}
