/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing15thnov_stage.dbscenarios;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Objects;

import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;

public class ViewAlltypesId implements Serializable {

    private Integer pkId;
    private Short byteCol;
    private Short shortCol;
    private Integer intCol;
    private Long longCol;
    private Double floatCol;
    private BigDecimal doubleCol;
    private BigDecimal bigdecCol;
    private Long bigintCol;
    private String charCol;
    private String stringCol;
    private String textCol;
    private String clobCol;
    private Date dateCol;
    private Time timeCol;
    @Type(type = "DateTime")
    private LocalDateTime datetimeCol;
    private Timestamp timestampCol;
    private Boolean booleanCol;
    private byte[] blobCol;

    public Integer getPkId() {
        return this.pkId;
    }

    public void setPkId(Integer pkId) {
        this.pkId = pkId;
    }

    public Short getByteCol() {
        return this.byteCol;
    }

    public void setByteCol(Short byteCol) {
        this.byteCol = byteCol;
    }

    public Short getShortCol() {
        return this.shortCol;
    }

    public void setShortCol(Short shortCol) {
        this.shortCol = shortCol;
    }

    public Integer getIntCol() {
        return this.intCol;
    }

    public void setIntCol(Integer intCol) {
        this.intCol = intCol;
    }

    public Long getLongCol() {
        return this.longCol;
    }

    public void setLongCol(Long longCol) {
        this.longCol = longCol;
    }

    public Double getFloatCol() {
        return this.floatCol;
    }

    public void setFloatCol(Double floatCol) {
        this.floatCol = floatCol;
    }

    public BigDecimal getDoubleCol() {
        return this.doubleCol;
    }

    public void setDoubleCol(BigDecimal doubleCol) {
        this.doubleCol = doubleCol;
    }

    public BigDecimal getBigdecCol() {
        return this.bigdecCol;
    }

    public void setBigdecCol(BigDecimal bigdecCol) {
        this.bigdecCol = bigdecCol;
    }

    public Long getBigintCol() {
        return this.bigintCol;
    }

    public void setBigintCol(Long bigintCol) {
        this.bigintCol = bigintCol;
    }

    public String getCharCol() {
        return this.charCol;
    }

    public void setCharCol(String charCol) {
        this.charCol = charCol;
    }

    public String getStringCol() {
        return this.stringCol;
    }

    public void setStringCol(String stringCol) {
        this.stringCol = stringCol;
    }

    public String getTextCol() {
        return this.textCol;
    }

    public void setTextCol(String textCol) {
        this.textCol = textCol;
    }

    public String getClobCol() {
        return this.clobCol;
    }

    public void setClobCol(String clobCol) {
        this.clobCol = clobCol;
    }

    public Date getDateCol() {
        return this.dateCol;
    }

    public void setDateCol(Date dateCol) {
        this.dateCol = dateCol;
    }

    public Time getTimeCol() {
        return this.timeCol;
    }

    public void setTimeCol(Time timeCol) {
        this.timeCol = timeCol;
    }

    public LocalDateTime getDatetimeCol() {
        return this.datetimeCol;
    }

    public void setDatetimeCol(LocalDateTime datetimeCol) {
        this.datetimeCol = datetimeCol;
    }

    public Timestamp getTimestampCol() {
        return this.timestampCol;
    }

    public void setTimestampCol(Timestamp timestampCol) {
        this.timestampCol = timestampCol;
    }

    public Boolean getBooleanCol() {
        return this.booleanCol;
    }

    public void setBooleanCol(Boolean booleanCol) {
        this.booleanCol = booleanCol;
    }

    public byte[] getBlobCol() {
        return this.blobCol;
    }

    public void setBlobCol(byte[] blobCol) {
        this.blobCol = blobCol;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ViewAlltypes)) return false;
        final ViewAlltypes viewAlltypes = (ViewAlltypes) o;
        return Objects.equals(getPkId(), viewAlltypes.getPkId()) &&
                Objects.equals(getByteCol(), viewAlltypes.getByteCol()) &&
                Objects.equals(getShortCol(), viewAlltypes.getShortCol()) &&
                Objects.equals(getIntCol(), viewAlltypes.getIntCol()) &&
                Objects.equals(getLongCol(), viewAlltypes.getLongCol()) &&
                Objects.equals(getFloatCol(), viewAlltypes.getFloatCol()) &&
                Objects.equals(getDoubleCol(), viewAlltypes.getDoubleCol()) &&
                Objects.equals(getBigdecCol(), viewAlltypes.getBigdecCol()) &&
                Objects.equals(getBigintCol(), viewAlltypes.getBigintCol()) &&
                Objects.equals(getCharCol(), viewAlltypes.getCharCol()) &&
                Objects.equals(getStringCol(), viewAlltypes.getStringCol()) &&
                Objects.equals(getTextCol(), viewAlltypes.getTextCol()) &&
                Objects.equals(getClobCol(), viewAlltypes.getClobCol()) &&
                Objects.equals(getDateCol(), viewAlltypes.getDateCol()) &&
                Objects.equals(getTimeCol(), viewAlltypes.getTimeCol()) &&
                Objects.equals(getDatetimeCol(), viewAlltypes.getDatetimeCol()) &&
                Objects.equals(getTimestampCol(), viewAlltypes.getTimestampCol()) &&
                Objects.equals(getBooleanCol(), viewAlltypes.getBooleanCol()) &&
                Objects.equals(getBlobCol(), viewAlltypes.getBlobCol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPkId(),
                getByteCol(),
                getShortCol(),
                getIntCol(),
                getLongCol(),
                getFloatCol(),
                getDoubleCol(),
                getBigdecCol(),
                getBigintCol(),
                getCharCol(),
                getStringCol(),
                getTextCol(),
                getClobCol(),
                getDateCol(),
                getTimeCol(),
                getDatetimeCol(),
                getTimestampCol(),
                getBooleanCol(),
                getBlobCol());
    }
}
