/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing15thnov_stage.dbscenarios;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;
import java.util.Objects;

public class VirtualTableId implements Serializable {

    private String charCol;
    private Date dateCol;
    private BigDecimal doubleCol;
    private BigDecimal bigdecCol;
    private String stringCol;
    private Short shortcol;

    public String getCharCol() {
        return this.charCol;
    }

    public void setCharCol(String charCol) {
        this.charCol = charCol;
    }

    public Date getDateCol() {
        return this.dateCol;
    }

    public void setDateCol(Date dateCol) {
        this.dateCol = dateCol;
    }

    public BigDecimal getDoubleCol() {
        return this.doubleCol;
    }

    public void setDoubleCol(BigDecimal doubleCol) {
        this.doubleCol = doubleCol;
    }

    public BigDecimal getBigdecCol() {
        return this.bigdecCol;
    }

    public void setBigdecCol(BigDecimal bigdecCol) {
        this.bigdecCol = bigdecCol;
    }

    public String getStringCol() {
        return this.stringCol;
    }

    public void setStringCol(String stringCol) {
        this.stringCol = stringCol;
    }

    public Short getShortcol() {
        return this.shortcol;
    }

    public void setShortcol(Short shortcol) {
        this.shortcol = shortcol;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof VirtualTable)) return false;
        final VirtualTable virtualTable = (VirtualTable) o;
        return Objects.equals(getCharCol(), virtualTable.getCharCol()) &&
                Objects.equals(getDateCol(), virtualTable.getDateCol()) &&
                Objects.equals(getDoubleCol(), virtualTable.getDoubleCol()) &&
                Objects.equals(getBigdecCol(), virtualTable.getBigdecCol()) &&
                Objects.equals(getStringCol(), virtualTable.getStringCol()) &&
                Objects.equals(getShortcol(), virtualTable.getShortcol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCharCol(),
                getDateCol(),
                getDoubleCol(),
                getBigdecCol(),
                getStringCol(),
                getShortcol());
    }
}
