/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing15thnov_stage.db123__.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ViewParamResponse implements Serializable {


    @ColumnAlias("USER ID")
    private Short userId;

    @ColumnAlias("USERNAME")
    private String username;

    @ColumnAlias("PASSWORD")
    private String password;

    @ColumnAlias("ROLE")
    private String role;

    public Short getUserId() {
        return this.userId;
    }

    public void setUserId(Short userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ViewParamResponse)) return false;
        final ViewParamResponse viewParamResponse = (ViewParamResponse) o;
        return Objects.equals(getUserId(), viewParamResponse.getUserId()) &&
                Objects.equals(getUsername(), viewParamResponse.getUsername()) &&
                Objects.equals(getPassword(), viewParamResponse.getPassword()) &&
                Objects.equals(getRole(), viewParamResponse.getRole());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getUserId(),
                getUsername(),
                getPassword(),
                getRole());
    }
}
