/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing15thnov_stage.db123__.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcedureInoutResponse implements Serializable {


    @ColumnAlias("CHARCOL_OUTPUT")
    private String charcolOutput;

    public String getCharcolOutput() {
        return this.charcolOutput;
    }

    public void setCharcolOutput(String charcolOutput) {
        this.charcolOutput = charcolOutput;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcedureInoutResponse)) return false;
        final ProcedureInoutResponse procedureInoutResponse = (ProcedureInoutResponse) o;
        return Objects.equals(getCharcolOutput(), procedureInoutResponse.getCharcolOutput());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCharcolOutput());
    }
}
