/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing15thnov_stage.wmstudio.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcedureSingleCursorAndOutResponse implements Serializable {


    @ColumnAlias("REGIONSDATA")
    private List<ProcedureSingleCursorAndOutResponseRegionsdata> regionsdata;

    @ColumnAlias("MAX_SAL")
    private Integer maxSal;

    public List<ProcedureSingleCursorAndOutResponseRegionsdata> getRegionsdata() {
        return this.regionsdata;
    }

    public void setRegionsdata(List<ProcedureSingleCursorAndOutResponseRegionsdata> regionsdata) {
        this.regionsdata = regionsdata;
    }

    public Integer getMaxSal() {
        return this.maxSal;
    }

    public void setMaxSal(Integer maxSal) {
        this.maxSal = maxSal;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcedureSingleCursorAndOutResponse)) return false;
        final ProcedureSingleCursorAndOutResponse procedureSingleCursorAndOutResponse = (ProcedureSingleCursorAndOutResponse) o;
        return Objects.equals(getRegionsdata(), procedureSingleCursorAndOutResponse.getRegionsdata()) &&
                Objects.equals(getMaxSal(), procedureSingleCursorAndOutResponse.getMaxSal());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getRegionsdata(),
                getMaxSal());
    }
}
